BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "PROGRAMMER" (
	"ID"	INTEGER NOT NULL,
	"NAME"	TEXT NOT NULL,
	"SURNAME"	TEXT NOT NULL,
	"BIRTHYEAR"	INTEGER NOT NULL,
	PRIMARY KEY("ID")
);
CREATE TABLE IF NOT EXISTS "STUDENT" (
	"ID"	INTEGER NOT NULL,
	"FIRDT_NAME"	TEXT NOT NULL,
	"LAST_NAME"	TEXT NOT NULL,
	"MAJOR"	TEXT NOT NULL,
	"EMAIL"	TEXT NOT NULL,
	"EXPECTED_GRAD_YEAR"	INTEGER NOT NULL,
	PRIMARY KEY("ID")
);
CREATE TABLE IF NOT EXISTS "COURSE_TIMES" (
	"CRN"	INTEGER NOT NULL,
	"MONDAY_START"	INTEGER,
	"MONDAY_END"	INTEGER,
	"TUESDAY_START"	INTEGER,
	"TUESDAY_END"	INTEGER,
	"WEDNESDAY_START"	INTEGER,
	"WEDNESDAY_END"	INTEGER,
	"THURSDAY_START"	INTEGER,
	"THURSDAY_END"	INTEGER,
	"FRIDAY_START"	INTEGER,
	"FRIDAY_END"	INTEGER,
	PRIMARY KEY("CRN")
);
CREATE TABLE IF NOT EXISTS "INSTRUCTOR" (
	"ID"	INTEGER NOT NULL,
	"FIRST_NAME"	TEXT NOT NULL,
	"LAST_NAME"	TEXT NOT NULL,
	"TITLE"	TEXT NOT NULL,
	"EMAIL"	TEXT NOT NULL,
	"DEPARTMENT"	TEXT NOT NULL,
	"YEAR_OF_HIRE"	INTEGER NOT NULL,
	PRIMARY KEY("ID")
);
CREATE TABLE IF NOT EXISTS "ADMIN" (
	"ID"	INTEGER NOT NULL,
	"FIRST_NAME"	TEXT NOT NULL,
	"LAST_NAME"	TEXT NOT NULL,
	"TITLE"	TEXT NOT NULL,
	"EMAIL"	TEXT NOT NULL,
	"OFFICE"	TEXT NOT NULL,
	PRIMARY KEY("ID")
);
CREATE TABLE IF NOT EXISTS "COURSE" (
	"CRN"	INTEGER NOT NULL,
	"TITLE"	TEXT NOT NULL,
	"DEPARTMENT"	TEXT NOT NULL,
	"TIME"	TEXT NOT NULL,
	"DAYS_OF_WEEK"	TEXT NOT NULL,
	"YEAR"	INTEGER NOT NULL,
	"CREDITS"	INTEGER NOT NULL,
	"SEMESTER"	TEXT NOT NULL,
	PRIMARY KEY("CRN")
);
INSERT INTO "PROGRAMMER" VALUES (1,'ADA','LOVELACE',1815);
INSERT INTO "PROGRAMMER" VALUES (2,'GRACE','HOPPER',1906);
INSERT INTO "PROGRAMMER" VALUES (3,'MARY KENNETH','KELLER',1913);
INSERT INTO "PROGRAMMER" VALUES (4,'EVELYN','BOYD GRANVILLE',1924);
INSERT INTO "PROGRAMMER" VALUES (5,'CAROL','SHAW',1955);
INSERT INTO "PROGRAMMER" VALUES (6,'Joey','Daermann',2002);
INSERT INTO "STUDENT" VALUES (1001,'Issac','Newton','BSAS','newtoni',1668);
INSERT INTO "STUDENT" VALUES (1002,'Marie','Curie','BSAS','curiem',1903);
INSERT INTO "STUDENT" VALUES (1003,'Nikola ','Tesla','BSEE','teslan',1878);
INSERT INTO "STUDENT" VALUES (1004,'Thomas','Eddison','BSEE','eddisont',1879);
INSERT INTO "STUDENT" VALUES (1005,'Jon ','von Neumann','BSCO','vonneumanj',1923);
INSERT INTO "STUDENT" VALUES (1006,'Grace','Hopper','BSCOS','hopperg',1928);
INSERT INTO "STUDENT" VALUES (1007,'Mae','Jemison','BSCH','jemisonm',1981);
INSERT INTO "STUDENT" VALUES (1008,'Mark','Dean','BSCO','deanm',1979);
INSERT INTO "STUDENT" VALUES (1009,'Michael','Faraday','BSAS','faradaym',1812);
INSERT INTO "STUDENT" VALUES (10010,'Ada','Lovelace','BCOS','lovelacea',1832);
INSERT INTO "INSTRUCTOR" VALUES (2001,'Joseph ','Fourier','Full Prof.','fourierj','BSEE',1820);
INSERT INTO "INSTRUCTOR" VALUES (2002,'Nelson','Patrick','Full Prof.','patrickn','HUSS',1994);
INSERT INTO "INSTRUCTOR" VALUES (2003,'Galileo','Galilei','Full Prof.','galileig','BSAS',1600);
INSERT INTO "INSTRUCTOR" VALUES (2004,'Alan','Turing','Associate Prof.','turinga','BSCO',1940);
INSERT INTO "INSTRUCTOR" VALUES (2005,'Katie','Bouman','Associate Prof.','boumank','BCOS',2019);
INSERT INTO "INSTRUCTOR" VALUES (2006,'Daniel','Bernoulli','Associate Prof.','bernoullid','BSME',1760);
INSERT INTO "ADMIN" VALUES (3001,'Margaret','Hamilton','President','hamiltonm','Dobbs 1600');
INSERT INTO "ADMIN" VALUES (3002,'Vera','Rubin','Registrar ','rubinv','Wentoworth 101');
INSERT INTO "COURSE" VALUES (11051,'Geology','ELEC','5:00','2',2023,4,'Spring');
INSERT INTO "COURSE" VALUES (12005,'Applied Programming Concepts','BSCE','8:00','3',2023,4,'Summer');
INSERT INTO "COURSE" VALUES (12006,'Computer Architecture','BSCE','10:00','3',2023,4,'Summer');
INSERT INTO "COURSE" VALUES (12008,'Engineering Calculus','BSCE','12:00','3',2023,4,'Summer');
INSERT INTO "COURSE" VALUES (12009,'English Literature','ELEC','2:00','2',2023,4,'Fall');
COMMIT;
